### ISSUE TITLE
Login/Cadastro

### ISSUE THREAD

**Issue by rikcav** [netrometro/UPE-2022.2-Equipe05#1]
Como usuário eu posso me autenticar no sistema para acessá-lo:

Para acessar as funcionalidades do sistema, é necessário que o usuário se cadastre como um novo usuário e faça login. O processo de cadastro permitirá que o usuário crie uma conta e defina suas credenciais de login. Depois de se cadastrar, o usuário poderá acessar o sistema fazendo login com seu email e senha. Este procedimento é fundamental para garantir a segurança e privacidade dos dados do usuário. Portanto, é importante que a funcionalidade de cadastro e login seja implementada corretamente.

**Comment by netrometro** [comment]
Olá,

Inicie a issue com a história do usuário, seguindo o modelo proposto no slide referente ao assunto. Depois você pode acrescentar informações. Dica sobre qual informação acrescentar: Imagine que não é você quem irá programar isso e a outra pessoa vai precisar de mais explicações para entender.

**Comment by lucas752** [comment]
Pull request #10
