### ISSUE TITLE
Contas

### ISSUE THREAD

**Issue by rikcav** [netrometro/UPE-2022.2-Equipe05#4]
Como usuário eu posso adicionar minhas contas para manter um registro das contas que devo pagar bem como das contas que ainda não paguei:

Esta funcionalidade permitirá que o usuário mantenha um registro das contas a serem pagas, permitindo que ele adicione suas contas. O usuário poderá criar e deletar suas contas, adicionando informações como título, valor, categoria, data de vencimento e descrição. Isso permitirá que o usuário mantenha um controle mais preciso de suas obrigações financeiras e evite atrasos no pagamento de suas contas. É importante que o sistema permita que o usuário acesse suas contas facilmente e possa atualizá-las ou excluí-las conforme necessário.

**Comment by lucas752** [comment]
Pull request #15
