### ISSUE TITLE
Caixinhas

### ISSUE THREAD

**Issue by rikcav** [netrometro/UPE-2022.2-Equipe05#5]
Como usuário eu posso criar uma caixinha para manter registro de uma compra futura que desejo realizar:

Esta funcionalidade permitirá que o usuário crie e mantenha um registro das compras que deseja realizar no futuro, permitindo que ele crie uma caixinha. O usuário poderá criar, atualizar e deletar suas caixinhas, adicionando informações como nome e valor do objetivo. Isso permitirá que o usuário planeje suas compras com antecedência e possa economizar o valor necessário antes de realizá-las. É importante que o sistema permita que o usuário acesse suas caixinhas facilmente e possa atualizá-las ou excluí-las conforme necessário.

**Comment by lucas752** [comment]
Pull Request #18
